spring:
  datasource:
    username: root
    password: jianai1314520
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
  data:
   gemfire:
    locator:
      host: localhost
      port: 31431