spring:
  datasource:
    url: jdbc:mysql://192.168.1.110:3306/batch?serverTimezone=Asia/Shanghai
    password: jianai1314520
    username: root
    data: classpath:data-delete.sql
    initialization-mode: always
  batch:
    job:
      enabled: false